package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Category;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    int updateByPrimaryKey(Category record);
}