package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.NotePerson;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface NotePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NOTE_PERSON
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    int deleteByPrimaryKey(@Param("notesId") Integer notesId, @Param("peopleId") Integer peopleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NOTE_PERSON
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    int insert(NotePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NOTE_PERSON
     *
     * @mbg.generated Sun May 02 15:31:25 EEST 2021
     */
    List<NotePerson> selectAll();
}